# Configurations
title:            Database Design
longtitle:        Database Design Project
author:           Muhammad Afif Abroory
email:            afifabroory@gmail.com
description: >
  My Database Design Project Collection

version:          1.0
gitbook_version:  3.2.3

url:              'https://afifabroory.github.io'
baseurl:          '/DatabaseDesign'
rss:              RSS

toc:
  enabled: true
  h_min: 1
  h_max: 3

# Search settings
tipue_search:
  include:
    pages: true
  exclude:
    files: [index.md, search.html]

# markdown render engine.
markdown:         kramdown
kramdown:
  auto_ids:               true
  input:                  GFM
  math_engine:            mathjax
  smart_quotes:           lsquo,rsquo,ldquo,rdquo
  toc_levels:             1..6
  syntax_highlighter:     rouge
  syntax_highlighter_opts:
    guess_lang:           true

markdown_ext:     markdown,mkdown,mkdn,mkd,md

# Permalinks
permalink:        /:categories/:year-:month-:day-:title:output_ext

exclude:
  - _drafts

destination:      ./_site
incremental:      false
regenerate:       true

plugins:
  - jekyll-feed
  - jemoji
